function timer_stop_kansu(score)

    ss = get(0, 'ScreenSize');
    % リザルトの図のバツ印を押されるとバグるので物理的に押せないようにする
    fig_result = ...
        figure('position', [ss(3)/3, ss(4)*3/4, ss(3)/3, ss(4)/3],...
        'Name', 'result', 'NumberTitle', 'off',...
        'ToolBar','none', 'MenuBar','none');

    % result_str = sprintf('Your score: %d\nPress any key to continue', score.value);
    result_str = sprintf('あなたの得点：%d\n任意のキーを押して終了☆', score.value);

  
    result_box = annotation('textbox', [0.2 0.1 0.6 0.15], ...
        'String', result_str, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'FontSize', 14, ...
        'FontWeight','bold', ...
        'Color', [0 0 0], ...       
        'BackgroundColor', [1 1 1 0.1], ...
        'EdgeColor', [0 0 0]);
    
    pause;  % 任意のキーを押すまで待機
    close all;  % これなくてもなんか消えるけど一応
% end
end